<a href="https://colab.research.google.com/github/1310NI14L/Bootcamp-From-Python-to-Machine-Learning/blob/main/notebook_J6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jour 7 - 21 Juillet 2026 : Introduction à NumPy

Bienvenue dans la semaine Data Science ! Aujourd'hui, nous découvrons **NumPy** (Numerical Python). C'est la bibliothèque de référence pour manipuler des données numériques en Python.

## 1. Pourquoi NumPy ?
En Python classique, on utilise des listes. Mais pour faire des calculs mathématiques sur de grandes quantités de données, les listes sont lentes. NumPy introduit le **ndarray** (tableau N-dimensionnel), qui est beaucoup plus rapide et occupe moins de mémoire.

In [1]:
import numpy as np # On importe numpy et on lui donne le surnom 'np' (une convention universelle)

# Création d'un tableau numpy à partir d'une liste
notes = np.array([12, 15, 9, 18, 11])
print(notes)
print("Type de l'objet :", type(notes))

[12 15  9 18 11]
Type de l'objet : <class 'numpy.ndarray'>


## 2. Dimensions et Formes (Shape)
Un tableau NumPy peut avoir 1 dimension (une ligne), 2 dimensions (une matrice avec lignes et colonnes) ou plus. La méthode `.shape` nous donne sa forme.

In [2]:
matrice = np.array([[1, 2, 3], [4, 5, 6]])
print(matrice)
print("Forme (lignes, colonnes) :", matrice.shape)

[[1 2 3]
 [4 5 6]]
Forme (lignes, colonnes) : (2, 3)


## 3. Opérations vectorisées
La vraie magie de NumPy : on peut faire des opérations mathématiques directement sur le tableau entier sans écrire de boucle `for` !

In [3]:
print("Notes + 2 (points bonus) :", notes + 2)
print("Notes multipliées par 2 :", notes * 2)
print("Moyenne des notes :", notes.mean())

Notes + 2 (points bonus) : [14 17 11 20 13]
Notes multipliées par 2 : [24 30 18 36 22]
Moyenne des notes : 13.0


---
## 🏆 Défi du Jour 7

1. Créez un tableau NumPy 1D appelé `temperatures` contenant les températures suivantes : 22.5, 18.0, 25.3, 19.8.
2. Affichez la forme (`shape`) de ce tableau.
3. Convertissez ces températures de Celsius en Fahrenheit en utilisant la formule vectorisée : `F = C * 9/5 + 32`.
4. Affichez la température maximale du tableau final (indice : utilisez `.max()`).

In [6]:
# Écrivez votre code pour le défi ici
temperatures = np.array([22.5, 18.0, 25.3, 19.8])
print(f"Forme du tableau : {temperatures.shape}")
F = (temperatures*9)/5 +32
print(f"Températures de Celsius en Fahrenheit : {F}")
print(f"Température maximale : {F.max()}")

Forme du tableau : (4,)
Températures de Celsius en Fahrenheit : [72.5  64.4  77.54 67.64]
Température maximale : 77.54
