<a href="https://colab.research.google.com/github/1310NI14L/Bootcamp-From-Python-to-Machine-Learning/blob/main/notebook_J7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jour 7 - 22 Juillet 2026 : NumPy Avancé

Aujourd'hui, nous allons voir comment manipuler la structure des tableaux et filtrer des données intelligemment.

## 1. Reshape (Changer la forme)
Très utile en Machine Learning pour réorganiser des données. Par exemple, transformer un tableau de 12 éléments en une matrice 3x4.

In [2]:
import numpy as np
a = np.arange(25) # Crée un tableau de 0 à 11
print("Tableau 1D initial :", a)

b = a.reshape(-1, 5) # 3 lignes, 4 colonnes
print("\nMatrice 3x4 :\n", b)

Tableau 1D initial : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Matrice 3x4 :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## 2. Masques booléens (Filtrage)
Le masque booléen consiste à filtrer un tableau en utilisant une condition. Cela renvoie un tableau de `True` et `False`, qu'on peut appliquer au tableau pour ne garder que les `True`.

In [16]:
ages = np.array([15, 22, 18, 30, 16, 25])

# Qui est majeur ?
majeur = ages >= 18
print("Masque booléen :", majeur)

# Appliquons le masque
print("Ages majeurs :", ages[majeur])

Masque booléen : [False  True  True  True False  True]
Ages majeurs : [22 18 30 25]


---
## 🏆 Défi du Jour 8

1. Créez un tableau `notes` contenant : [8, 12, 15, 9, 17, 5, 11].
2. Utilisez un masque booléen pour créer un nouveau tableau `notes_valides` ne contenant que les notes supérieures ou égales à 10.
3. Affichez `notes_valides`.

In [9]:
# Écrivez votre code pour le défi ici
notes = np.array([8, 12, 15, 9, 17, 5, 11, 8])
notes_sup_10 = notes >= 10
print(f"Notes : {notes}")
print(f"Masque de filtrage : {notes_sup_10}")
print(f"Notes valides : {notes[notes_sup_10]}")
print(f"Matrice des notes valides :\n{notes[notes_sup_10].reshape(-1,2)}")

Notes : [ 8 12 15  9 17  5 11  8]
Masque de filtrage : [False  True  True False  True False  True False]
Notes valides : [12 15 17 11]
Matrice des notes valides :
[[12 15]
 [17 11]]
